### ISSUE TITLE
Добавить взаимодействие с Яндекс.Деньги

### ISSUE THREAD

**Issue by ramm** [66ru/payback#3]
Прямая работа с Я.Деньгами.

Подумать, как передавать на клиентов список доступных валют, чтобы пользователь заранее выбирал, чем платить, чтобы знать, куда его дальше прокидывать.

**Comment by ramm** [comment]
В общем случае система "валют" должна работать так:
- Мы на payback определяем список "валют", доступных для выбора пользователям
- Для каждой "валюты" указываем, в какой платежный бэкенд (робокасса, яндекс.деньги) передать процессинг запроса
- Соответственно надо уметь сообщать "клиенту" (сайт, использующий сервис) список доступных валют и требовать передачи идентификатора, помимо суммы платежа.

Вообще чисто теоретически — эта задача ставилась изначально при разработке payback, но на практике мы никогла её работу не проверяли.

Тестово выбор "валюты" между "Яндекс.Деньги" (бэкенд я.деньги) и "другие средства" (бэкенд робокасса) можно реализовать на /doska/ — оплата "в топ" в разделе недвижимости.

**Comment by nskeip** [comment]
> Подумать, как передавать на клиентов список доступных валют

Во view для этого есть curr_list.
В урлах: url(r'currencies/$', 'currs_list', name='currs_list').
Доожно работать. Тестов почему-то нет. Собственно, видимо ввиду микроскопического размера вьюшки.

> Соответственно надо уметь сообщать "клиенту" (сайт, использующий сервис) список доступных валют и требовать передачи идентификатора, помимо суммы платежа

В формах вот что сделано:

currency_code = forms.ChoiceField(choices=[(c, c) for c in Currency.get_listing()])

То есть уже требуется валидная валюта и необходима лишь правильная настройка на сервере. Каюсь, в период запуска payback'а все валюты были обозваны Яндекс-деньгами :))))))

**Comment by ramm** [comment]
Спасибо за инсайт. :)

Я поэтому и написал, что "на практике не проверяли".

**Comment by zedxter** [comment]
Бэкенд яндекс-денег готов. Авторизация проходит, деньги принимаются. Нужна тонкая настройка как самого бэкенда, так и настройка приложения из личного кабинета яндекс.денег. Отпишу в Wiki.
